import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@mantine/core/styles.css";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/components/providers";
import { lazy, Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ECOMARCE-ADMIN",
  description: "Generated by create next app",
};

// Lazy load the Navbar component with better error handling
const Navbar = lazy(() =>
  import("@/components/navbar").catch((error) => {
    console.error("Failed to load navbar:", error);
    // Return a fallback navbar component
    return Promise.resolve({
      default: () => (
        <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-sm">
          <nav className="container mx-auto px-4">
            <div className="flex justify-between items-center h-16">
              <div className="text-xl font-bold">Admin Panel</div>
              <div className="hidden sm:flex gap-4">
                <a
                  href="/admin/login"
                  className="px-4 py-2 border rounded hover:bg-gray-50"
                >
                  Admin Login
                </a>
                <a
                  href="/admin/dashboard"
                  className="px-4 py-2 border rounded hover:bg-gray-50"
                >
                  Dashboard
                </a>
              </div>
            </div>
          </nav>
        </header>
      ),
    });
  })
);

// Enhanced loading skeleton for navbar with admin-specific elements
const NavbarSkeleton = () => (
  <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-sm animate-pulse">
    <nav className="container mx-auto px-4">
      <div className="flex justify-between items-center h-16">
        {/* Logo skeleton */}
        <div className="w-32 h-8 bg-gray-200 rounded"></div>

        {/* Desktop navigation skeleton */}
        <div className="hidden sm:flex gap-4">
          <div className="w-24 h-10 bg-gray-200 rounded"></div>
          <div className="w-32 h-10 bg-gray-200 rounded"></div>
        </div>

        {/* Mobile menu button skeleton */}
        <div className="sm:hidden w-6 h-6 bg-gray-200 rounded"></div>
      </div>
    </nav>
  </header>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider>
          <Providers>
            {/* Lazy loaded Navbar with enhanced skeleton */}
            <Suspense fallback={<NavbarSkeleton />}>
              <Navbar />
            </Suspense>

            {children}

            <Toaster />
          </Providers>
        </MantineProvider>
      </body>
    </html>
  );
}
